import type { PlaceRecord } from '../types';

export const PLACE_DATASET: PlaceRecord[] = [
  {
    id: 'seoul-forest',
    name: 'Seoul Forest',
    location: 'Seongdong-gu, Seoul',
    summary: 'Large urban park with trees, water edges, and long walking routes.',
    tags: {
      element: ['wood', 'water'],
      nature_ratio: 5,
      brightness: 3,
      crowd: 3,
      material: ['wood', 'water'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'naksan-park',
    name: 'Naksan Park',
    location: 'Jongno-gu, Seoul',
    summary: 'Hillside park with walking walls, skyline views, and daylight movement.',
    tags: {
      element: ['wood', 'fire'],
      nature_ratio: 4,
      brightness: 4,
      crowd: 3,
      material: ['wood', 'stone'],
      activity: ['explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'bukhan-trail',
    name: 'Bukhansan Dulle-gil',
    location: 'Eunpyeong-gu, Seoul',
    summary: 'Forest-heavy trail focused on walking, breathing room, and tree cover.',
    tags: {
      element: ['wood'],
      nature_ratio: 5,
      brightness: 3,
      crowd: 2,
      material: ['wood', 'earth'],
      activity: ['explore'],
      time_preference: ['day'],
      temperature_feel: 'cool',
      structure: 'organic',
    },
  },
  {
    id: 'cheonggyecheon',
    name: 'Cheonggyecheon Stream',
    location: 'Jongno-gu, Seoul',
    summary: 'Linear water corridor through downtown with soft movement and reflection.',
    tags: {
      element: ['water', 'wood'],
      nature_ratio: 3,
      brightness: 3,
      crowd: 4,
      material: ['water', 'stone'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'changgyeong-palace',
    name: 'Changgyeonggung Palace Garden',
    location: 'Jongno-gu, Seoul',
    summary: 'Historic garden with trees, ponds, and contained circulation.',
    tags: {
      element: ['wood', 'earth'],
      nature_ratio: 4,
      brightness: 3,
      crowd: 2,
      material: ['wood', 'stone'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'ddp',
    name: 'Dongdaemun Design Plaza',
    location: 'Jung-gu, Seoul',
    summary: 'Bright, high-visibility urban destination with strong lighting and circulation.',
    tags: {
      element: ['fire', 'metal'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 5,
      material: ['metal', 'glass'],
      activity: ['explore'],
      time_preference: ['night'],
      temperature_feel: 'warm',
      structure: 'linear',
    },
  },
  {
    id: 'lotte-sky',
    name: 'Lotte World Tower Seoul Sky',
    location: 'Songpa-gu, Seoul',
    summary: 'High-elevation observatory with bright city views and strong visibility.',
    tags: {
      element: ['fire', 'metal'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 4,
      material: ['metal', 'glass'],
      activity: ['explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'gwanghwamun-square',
    name: 'Gwanghwamun Square',
    location: 'Jongno-gu, Seoul',
    summary: 'Open civic axis with sunlight, visibility, and broad movement lanes.',
    tags: {
      element: ['fire', 'earth'],
      nature_ratio: 1,
      brightness: 5,
      crowd: 4,
      material: ['stone'],
      activity: ['explore'],
      time_preference: ['day'],
      temperature_feel: 'warm',
      structure: 'linear',
    },
  },
  {
    id: 'hongdae-street',
    name: 'Hongdae Main Street',
    location: 'Mapo-gu, Seoul',
    summary: 'Dense nightlife corridor with social energy, brightness, and fast pacing.',
    tags: {
      element: ['fire'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 5,
      material: ['glass'],
      activity: ['explore'],
      time_preference: ['night'],
      temperature_feel: 'warm',
      structure: 'mixed',
    },
  },
  {
    id: 'gyeongbokgung',
    name: 'Gyeongbokgung Palace',
    location: 'Jongno-gu, Seoul',
    summary: 'Grounded historic complex with strong axis, open courtyards, and stability.',
    tags: {
      element: ['earth'],
      nature_ratio: 2,
      brightness: 4,
      crowd: 3,
      material: ['stone', 'earth'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'linear',
    },
  },
  {
    id: 'changdeokgung-secret-garden',
    name: 'Changdeokgung Secret Garden',
    location: 'Jongno-gu, Seoul',
    summary: 'Balanced historic garden with contained routes and grounding atmosphere.',
    tags: {
      element: ['earth', 'wood', 'water'],
      nature_ratio: 4,
      brightness: 3,
      crowd: 2,
      material: ['stone', 'wood', 'water'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'national-museum',
    name: 'National Museum of Korea',
    location: 'Yongsan-gu, Seoul',
    summary: 'Grounded cultural site with open forecourt and stable interior rhythm.',
    tags: {
      element: ['earth', 'metal'],
      nature_ratio: 2,
      brightness: 3,
      crowd: 2,
      material: ['stone', 'metal'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'linear',
    },
  },
  {
    id: 'seongbuk-dong',
    name: 'Seongbuk-dong Walk',
    location: 'Seongbuk-gu, Seoul',
    summary: 'Quiet residential-cultural area with slow pace and grounded movement.',
    tags: {
      element: ['earth', 'wood'],
      nature_ratio: 3,
      brightness: 2,
      crowd: 1,
      material: ['stone', 'wood'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'park-hyatt-seoul',
    name: 'Park Hyatt Seoul Lobby',
    location: 'Gangnam-gu, Seoul',
    summary: 'Minimal, structured interior for quiet decision-making and focus.',
    tags: {
      element: ['metal'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 2,
      material: ['metal', 'glass', 'stone'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'conrad-seoul',
    name: 'Conrad Seoul',
    location: 'Yeongdeungpo-gu, Seoul',
    summary: 'Finance-district hotel with ordered circulation and modern finishes.',
    tags: {
      element: ['metal', 'water'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 3,
      material: ['metal', 'glass'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'fairmont-seoul',
    name: 'Fairmont Ambassador Seoul',
    location: 'Yeongdeungpo-gu, Seoul',
    summary: 'Clean-lined hospitality setting with high order and visual control.',
    tags: {
      element: ['metal'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 2,
      material: ['metal', 'glass', 'stone'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['flagship_site'],
    },
  },
  {
    id: 'the-plaza-seoul',
    name: 'The Plaza Seoul',
    location: 'Jung-gu, Seoul',
    summary: 'City Hall-adjacent flagship hotel with strong financial and ceremonial city energy.',
    tags: {
      element: ['metal', 'earth'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 3,
      material: ['metal', 'glass', 'stone'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['flagship_site', 'sheltered_site'],
    },
  },
  {
    id: 'signiel-seoul',
    name: 'Signiel Seoul',
    location: 'Songpa-gu, Seoul',
    summary: 'Ultra-high-rise luxury hotel with strong skyline, visibility, and concentrated metal-fire energy.',
    tags: {
      element: ['metal', 'fire'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 3,
      material: ['metal', 'glass'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['flagship_site'],
    },
  },
  {
    id: 'westin-josun-seoul',
    name: 'The Westin Josun Seoul',
    location: 'Jung-gu, Seoul',
    summary: 'Historic prestige hotel near Sogong-dong and ceremonial city core, suited to wealth and conclusion energy.',
    tags: {
      element: ['metal', 'earth'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 3,
      material: ['stone', 'metal', 'glass'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'neutral',
      structure: 'linear',
      fengshui_signals: ['flagship_site', 'sheltered_site'],
    },
  },
  {
    id: 'parnas-hotel-gangnam',
    name: 'Grand InterContinental Seoul Parnas',
    location: 'Gangnam-gu, Seoul',
    summary: 'Samseong-dong flagship hotel associated with flowing business energy and water-driven networking atmosphere.',
    tags: {
      element: ['water', 'metal'],
      nature_ratio: 0,
      brightness: 3,
      crowd: 3,
      material: ['water', 'glass', 'metal'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'mixed',
      fengshui_signals: ['flagship_site', 'water_edge'],
    },
  },
  {
    id: 'inwangsan-peak',
    name: 'Inwangsan Peak',
    location: 'Jongno-gu, Seoul',
    summary: 'Rock-heavy summit route with visual clarity and decisive atmosphere.',
    tags: {
      element: ['metal', 'earth'],
      nature_ratio: 3,
      brightness: 4,
      crowd: 2,
      material: ['stone', 'metal'],
      activity: ['explore'],
      time_preference: ['day'],
      temperature_feel: 'cool',
      structure: 'organic',
    },
  },
  {
    id: 'jamsil-hangang',
    name: 'Jamsil Hangang Park',
    location: 'Songpa-gu, Seoul',
    summary: 'Wide riverfront for cooling down, decompression, and long-view recovery.',
    tags: {
      element: ['water'],
      nature_ratio: 4,
      brightness: 3,
      crowd: 3,
      material: ['water', 'stone'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'oksu-riverside',
    name: 'Oksu Riverside Walk',
    location: 'Seongdong-gu, Seoul',
    summary: 'Quieter waterside route with lower crowd and steady reflective pacing.',
    tags: {
      element: ['water'],
      nature_ratio: 4,
      brightness: 2,
      crowd: 1,
      material: ['water'],
      activity: ['rest'],
      time_preference: ['night'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'josun-palace',
    name: 'Josun Palace Lounge',
    location: 'Gangnam-gu, Seoul',
    summary: 'Quiet upscale interior with water accents and slower pacing.',
    tags: {
      element: ['water', 'metal'],
      nature_ratio: 0,
      brightness: 3,
      crowd: 2,
      material: ['water', 'glass', 'metal'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'mixed',
    },
  },
  {
    id: 'seolleung-park',
    name: 'Seolleung and Jeongneung Park',
    location: 'Gangnam-gu, Seoul',
    summary: 'Low-noise green space useful for resetting pace during a workday.',
    tags: {
      element: ['water', 'wood', 'earth'],
      nature_ratio: 4,
      brightness: 3,
      crowd: 2,
      material: ['wood', 'earth'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'deoksugung-stonewall',
    name: 'Deoksugung Stonewall Walk',
    location: 'Jung-gu, Seoul',
    summary: 'Lower-intensity city walk with shade, stone texture, and cooling pace.',
    tags: {
      element: ['water', 'earth'],
      nature_ratio: 2,
      brightness: 2,
      crowd: 2,
      material: ['stone', 'wood'],
      activity: ['rest'],
      time_preference: ['day'],
      temperature_feel: 'cool',
      structure: 'linear',
    },
  },
  {
    id: 'yangjae-citizens-forest',
    name: 'Yangjae Citizens Forest',
    location: 'Seocho-gu, Seoul',
    summary: 'A dense urban forest with tree-lined walking paths and stable green vitality.',
    tags: {
      element: ['wood'],
      nature_ratio: 5,
      brightness: 3,
      crowd: 2,
      material: ['wood', 'earth'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'gwanghwamun-kyobo',
    name: 'Gwanghwamun Kyobo Book Centre',
    location: 'Jongno-gu, Seoul',
    summary: 'A book-lined interior where paper, knowledge, and calm forward movement gather together.',
    tags: {
      element: ['wood', 'earth'],
      nature_ratio: 1,
      brightness: 3,
      crowd: 3,
      material: ['wood'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'yangjae-flower-market',
    name: 'Yangjae Flower Market',
    location: 'Seocho-gu, Seoul',
    summary: 'A high-density plant and flower market overflowing with fresh life energy.',
    tags: {
      element: ['wood'],
      nature_ratio: 5,
      brightness: 4,
      crowd: 3,
      material: ['wood', 'water'],
      activity: ['explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'organic',
    },
  },
  {
    id: 'gangnam-station',
    name: 'Gangnam Station',
    location: 'Gangnam-gu, Seoul',
    summary: 'Fast, bright, high-energy district filled with crowd heat and urban stimulation.',
    tags: {
      element: ['fire'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 5,
      material: ['glass'],
      activity: ['explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'warm',
      structure: 'mixed',
    },
  },
  {
    id: 'sungnyemun',
    name: 'Sungnyemun',
    location: 'Jung-gu, Seoul',
    summary: 'A historically open civic gateway with bright exposure and strong urban fire energy.',
    tags: {
      element: ['fire', 'earth'],
      nature_ratio: 1,
      brightness: 4,
      crowd: 4,
      material: ['stone'],
      activity: ['explore'],
      time_preference: ['day'],
      temperature_feel: 'warm',
      structure: 'linear',
    },
  },
  {
    id: 'teheran-ro',
    name: 'Teheran-ro',
    location: 'Gangnam-gu, Seoul',
    summary: 'A dense corporate corridor carrying speed, status, visibility, and modern fire energy.',
    tags: {
      element: ['fire', 'metal'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 4,
      material: ['metal', 'glass'],
      activity: ['explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'warm',
      structure: 'linear',
    },
  },
  {
    id: 'imperial-palace-lobby',
    name: 'Imperial Palace Lobby',
    location: 'Gangnam-gu, Seoul',
    summary: 'A dramatic lobby with heavy ornament, gold-toned light, and ceremonial hotel energy.',
    tags: {
      element: ['fire', 'earth'],
      nature_ratio: 0,
      brightness: 5,
      crowd: 3,
      material: ['glass', 'stone'],
      activity: ['rest'],
      time_preference: ['day', 'night'],
      temperature_feel: 'warm',
      structure: 'linear',
      fengshui_signals: ['flagship_site'],
    },
  },
  {
    id: 'namsan-walk',
    name: 'Namsan Walk',
    location: 'Yongsan-gu, Seoul',
    summary: 'A central Seoul slope with grounded terrain and steady stabilizing presence.',
    tags: {
      element: ['earth', 'fire'],
      nature_ratio: 3,
      brightness: 3,
      crowd: 2,
      material: ['stone', 'earth'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'jogyesa',
    name: 'Jogyesa',
    location: 'Jongno-gu, Seoul',
    summary: 'A grounded temple precinct that helps settle floating energy and restore inner center.',
    tags: {
      element: ['earth'],
      nature_ratio: 2,
      brightness: 2,
      crowd: 2,
      material: ['stone', 'earth'],
      activity: ['rest'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'jangchung-dong',
    name: 'Jangchung-dong',
    location: 'Jung-gu, Seoul',
    summary: 'A quietly stable slope-zone that feels weighty and centered rather than flashy.',
    tags: {
      element: ['earth'],
      nature_ratio: 2,
      brightness: 2,
      crowd: 2,
      material: ['earth', 'stone'],
      activity: ['rest'],
      time_preference: ['day'],
      temperature_feel: 'neutral',
      structure: 'mixed',
    },
  },
  {
    id: 'apgujeong-dosan-daero',
    name: 'Apgujeong Dosan-daero',
    location: 'Gangnam-gu, Seoul',
    summary: 'A luxury brand corridor associated with prestige, edge, and controlled social power.',
    tags: {
      element: ['metal'],
      nature_ratio: 0,
      brightness: 4,
      crowd: 3,
      material: ['metal', 'glass', 'stone'],
      activity: ['explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['flagship_site'],
    },
  },
  {
    id: 'banpo-hangang-park',
    name: 'Banpo Hangang Park',
    location: 'Seocho-gu, Seoul',
    summary: 'A wide riverside park that cools overheated energy and restores flexible flow.',
    tags: {
      element: ['water'],
      nature_ratio: 4,
      brightness: 3,
      crowd: 3,
      material: ['water', 'stone'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['water_edge'],
    },
  },
  {
    id: 'seokchon-lake',
    name: 'Seokchon Lake',
    location: 'Songpa-gu, Seoul',
    summary: 'A calm urban lake that helps soften heat, rigid thinking, and emotional overload.',
    tags: {
      element: ['water'],
      nature_ratio: 4,
      brightness: 2,
      crowd: 3,
      material: ['water'],
      activity: ['rest', 'explore'],
      time_preference: ['day', 'night'],
      temperature_feel: 'cool',
      structure: 'linear',
      fengshui_signals: ['water_edge'],
    },
  },
  {
    id: 'seochon-walk',
    name: 'Seochon Walk',
    location: 'Jongno-gu, Seoul',
    summary: 'A lower, quieter neighborhood texture that supports cooling and emotional easing.',
    tags: {
      element: ['water', 'earth'],
      nature_ratio: 2,
      brightness: 2,
      crowd: 2,
      material: ['stone', 'water'],
      activity: ['rest', 'explore'],
      time_preference: ['day'],
      temperature_feel: 'cool',
      structure: 'mixed',
    },
  },
  ];
